# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e794cc2536cac8210715e374f77d6b35d364f6a7bd1e779daccf4a2b82ad623865d9a2d6b05208ab80a97c36bafd9fae95846387d7305ab7b4d38305867dc00b
  moip_token: DYKOGNOLSEHCE9COAPPGWMC00DMC9IEC
  moip_key: TAFOKVJ2Q7WQBZADSVOTNOIOBWMGMVUR9EONF1W4
  moip_auth: Basic RFlLT0dOT0xTRUhDRTlDT0FQUEdXTUMwMERNQzlJRUM6VEFGT0tWSjJRN1dRQlpBRFNWT1ROT0lPQldNR01WVVI5RU9ORjFXNA==
  moip_domain: https://sandbox.moip.com.br/v2
  moip_env: sandbox
  moip_app_token: OAuth jdyi6e28vdyz2l8e1nss0jadh1j4ay2
  facebook_id: 1696671210617842
  facebook_secret: 139c0aa70326780fbc8cd2dc098d2cdb
  truppiemail_domain: truppie.com
  truppiemail_username: foo
  truppiemail_password: test
  redis_url: "redis://localhost:6379"
  stripe_key: sk_test_E9OwGy2A29NqDHrFdunOdmOI

test:
  secret_key_base: 645b2a9bd42bb2c8351896f18bec4391d27fb2dc23036bf3883dd21a330bc72f638e09445dc1d02f45bb15842bb7a932c4ecea6edffa3bc73abbdf578d381c33
  moip_token: DYKOGNOLSEHCE9COAPPGWMC00DMC9IEC
  moip_key: TAFOKVJ2Q7WQBZADSVOTNOIOBWMGMVUR9EONF1W4
  moip_auth: Basic RFlLT0dOT0xTRUhDRTlDT0FQUEdXTUMwMERNQzlJRUM6VEFGT0tWSjJRN1dRQlpBRFNWT1ROT0lPQldNR01WVVI5RU9ORjFXNA==
  moip_domain: https://sandbox.moip.com.br/v2
  moip_env: sandbox
  moip_app_token: OAuth jdyi6e28vdyz2l8e1nss0jadh1j4ay2
  facebook_id: 1696671210617842
  facebook_secret: 139c0aa70326780fbc8cd2dc098d2cdb
  truppiemail_domain: whatever.com
  truppiemail_username: foo
  truppiemail_password: test
  redis_url: "redis://localhost:6379"
  stripe_key: sk_test_E9OwGy2A29NqDHrFdunOdmOI
 
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  moip_token: <%= ENV["moip_token"] %>
  moip_key: <%= ENV["moip_key"] %>
  moip_auth: <%= ENV["moip_auth"] %>
  facebook_id: <%= ENV["facebook_id"] %>
  facebook_secret: <%= ENV["facebook_secret"] %>
  truppiemail_domain: <%= ENV["truppiemail_domain"] %>
  truppiemail_username: <%= ENV['SENDGRID_USERNAME'] %>
  truppiemail_password: <%= ENV['SENDGRID_PASSWORD'] %>
  moip_domain: <%= ENV['MOIP_DOMAIN'] %>
  moip_env: <%= ENV['MOIP_ENV'] %>
  moip_app_token: <%= ENV['MOIP_APP_TOKEN'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  stripe_key: <%= ENV['STRIPE_KEY'] %>
